Fix compiler warnings on platforms where char is unsigned
If char is unsigned, there were two warnings that made the build fail
because of `-Werror=sign-promo`:

Init.cpp: In function 'void SetDealTables(ThreadData*)':
Init.cpp:534:9: error: conversion to 'signed char' from 'char' may change the sign of the result [-Werror=sign-conversion]
         static_cast<char>(handLookup[s][topBitNo]);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TransTableL.cpp: In member function ‘void TransTableL::PrintNodeValues(std::ofstream&, const nodeCardsType&) const’:
TransTableL.cpp:1028:24: error: passing ‘char’ chooses ‘int’ over ‘unsigned int’ [-Werror=sign-promo]
     to_string(np.lbound) << " to " <<
                        ^